# Generated by Django 5.1.6 on 2025-03-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_eventcancellation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='additional_options',
        ),
        migrations.AddField(
            model_name='venue',
            name='additional_options',
            field=models.ManyToManyField(blank=True, related_name='events', to='api.additionaloption'),
        ),
    ]
