# Generated by Django 5.1.6 on 2025-03-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_event_additional_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaloption',
            name='type',
            field=models.CharField(choices=[('referee', 'Referee'), ('medical_officer', 'Medical Officer'), ('others', 'Others')], max_length=20),
        ),
    ]
