# Generated by Django 5.1.6 on 2025-03-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_event_image_event_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='image_url',
            new_name='image',
        ),
    ]
