# Generated by Django 5.1.6 on 2025-03-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaloption',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
