# Generated by Django 5.1.6 on 2025-03-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_additionaloption_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
