# Generated by Django 5.1.6 on 2025-03-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_venue_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='location',
        ),
        migrations.AddField(
            model_name='venue',
            name='latitude',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='venue',
            name='longitude',
            field=models.FloatField(default=1),
        ),
    ]
