# Generated by Django 5.1.6 on 2025-03-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_venue_location_venue_latitude_venue_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
