# Generated by Django 5.1.6 on 2025-03-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_post_body_text_post_participants_post_repost_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='share_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
