# Generated by Django 5.1.6 on 2025-03-19 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_post_is_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='repost_reason',
            new_name='report_reason',
        ),
    ]
