# Generated by Django 5.1.6 on 2025-03-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_comment_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repost',
            name='content',
            field=models.TextField(default='Repost'),
        ),
        migrations.AlterField(
            model_name='repost',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repost',
            name='voice',
            field=models.URLField(blank=True, null=True),
        ),
    ]
