# Generated by Django 5.1.6 on 2025-03-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_repost_is_reported_repost_report_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repost',
            name='Likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repost',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_reposts', to='api.userprofile'),
        ),
    ]
