# Generated by Django 5.1.6 on 2025-03-22 22:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_repost_likes_repost_liked_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepostComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_repost_comments', to='api.userprofile')),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_repost_comments', to='api.userprofile')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.repostcomment')),
                ('repost', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='api.repost')),
            ],
        ),
    ]
