# Generated by Django 5.1.6 on 2025-03-24 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_event_team_winner_eventstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_stats',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_detail', to='api.eventstats'),
        ),
    ]
