# Generated by Django 5.1.6 on 2025-03-24 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_event_event_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='team_winner',
        ),
    ]
