# Generated by Django 5.1.6 on 2025-03-24 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_event_team_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstats',
            name='team_winner',
            field=models.CharField(choices=[('A', 'Team A'), ('B', 'Team B'), ('ND', 'Not Determined')], default='ND', max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_stats',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_detail', to='api.eventstats'),
        ),
        migrations.AlterField(
            model_name='eventstats',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stats', to='api.event'),
        ),
    ]
