# Generated by Django 5.1.6 on 2025-03-24 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_eventstats_team_winner_alter_event_event_stats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_stats',
        ),
        migrations.DeleteModel(
            name='EventStats',
        ),
    ]
