# Generated by Django 5.1.6 on 2025-03-24 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_event_event_stats_delete_eventstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_winner', models.CharField(choices=[('A', 'Team A'), ('B', 'Team B'), ('ND', 'Not Determined')], default='ND', max_length=2)),
                ('team_a_total_attempts', models.PositiveIntegerField(default=0)),
                ('team_a_attempts_on_target', models.PositiveIntegerField(default=0)),
                ('team_a_fouls_committed', models.PositiveIntegerField(default=0)),
                ('team_a_yellow_cards', models.PositiveIntegerField(default=0)),
                ('team_a_red_cards', models.PositiveIntegerField(default=0)),
                ('team_a_offsides', models.PositiveIntegerField(default=0)),
                ('team_a_corners', models.PositiveIntegerField(default=0)),
                ('team_a_possession', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('team_b_total_attempts', models.PositiveIntegerField(default=0)),
                ('team_b_attempts_on_target', models.PositiveIntegerField(default=0)),
                ('team_b_fouls_committed', models.PositiveIntegerField(default=0)),
                ('team_b_yellow_cards', models.PositiveIntegerField(default=0)),
                ('team_b_red_cards', models.PositiveIntegerField(default=0)),
                ('team_b_offsides', models.PositiveIntegerField(default=0)),
                ('team_b_corners', models.PositiveIntegerField(default=0)),
                ('team_b_possession', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stats', to='api.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_stats',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_detail', to='api.eventstats'),
        ),
    ]
