# Generated by Django 5.1.6 on 2025-05-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_eventstats_event_event_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancellation_period_hours',
            field=models.PositiveIntegerField(default=24, help_text='Hours before event when cancellation is allowed'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='removed_players',
            field=models.ManyToManyField(blank=True, related_name='removed_from_events', to='api.userprofile'),
        ),
    ]
