# Generated by Django 5.1.6 on 2025-05-03 08:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_noshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noshow',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
