# Generated by Django 5.1.6 on 2025-06-22 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='receiver',
        ),
        migrations.AddField(
            model_name='notification',
            name='followed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_as_followed', to='api.userprofile'),
        ),
        migrations.AddField(
            model_name='notification',
            name='follower',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_as_follower', to='api.userprofile'),
        ),
    ]
