# Generated by Django 5.1.6 on 2025-07-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_post_views_repost_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saved_posts',
            field=models.ManyToManyField(blank=True, related_name='saved_by_users', to='api.post'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='saved_reposts',
            field=models.ManyToManyField(blank=True, related_name='saved_by_users', to='api.repost'),
        ),
    ]
