# Generated by Django 5.1.6 on 2025-09-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_userprofile_saved_posts_userprofile_saved_reposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='event',
            name='popularity_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
