# Generated by Django 5.1.6 on 2025-09-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_event_latitude_event_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(choices=[('Abu Dhabi', 'Abu Dhabi'), ('Ajman', 'Ajman'), ('Al Ain', 'Al Ain'), ('Dubai', 'Dubai'), ('Fujairah', 'Fujairah'), ('Hatta', 'Hatta'), ('Khor Fakkan', 'Khor Fakkan'), ('Ras Al Khaimah', 'Ras Al Khaimah'), ('Sharjah', 'Sharjah'), ('Umm Al Quwain', 'Umm Al Quwain')], default='Dubai', max_length=50),
        ),
    ]
