# Generated by Django 5.1.6 on 2025-09-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_event_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='image3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='image4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='team_c_members',
            field=models.ManyToManyField(blank=True, related_name='team_c_members', to='api.userprofile'),
        ),
        migrations.AddField(
            model_name='event',
            name='team_d_members',
            field=models.ManyToManyField(blank=True, related_name='team_d_members', to='api.userprofile'),
        ),
        migrations.AddField(
            model_name='event',
            name='team_e_members',
            field=models.ManyToManyField(blank=True, related_name='team_e_members', to='api.userprofile'),
        ),
        migrations.AddField(
            model_name='event',
            name='team_f_members',
            field=models.ManyToManyField(blank=True, related_name='team_f_members', to='api.userprofile'),
        ),
        migrations.AddField(
            model_name='event',
            name='team_g_members',
            field=models.ManyToManyField(blank=True, related_name='team_g_members', to='api.userprofile'),
        ),
        migrations.AddField(
            model_name='event',
            name='team_h_members',
            field=models.ManyToManyField(blank=True, related_name='team_h_members', to='api.userprofile'),
        ),
    ]
