# Generated by Django 5.1.6 on 2025-09-06 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='teams_number',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
