# Generated by Django 5.1.6 on 2025-09-09 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_post_extra_title_1_post_extra_title_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Venue',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 'Available'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.venue'),
        ),
    ]
