# Generated by Django 5.1.6 on 2025-11-22 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_deleterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaloption',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='additional_options', to='api.event'),
        ),
    ]
