# Generated by Django 5.1.6 on 2025-12-29 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_additionaloption_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaloption',
            name='is_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='additionaloption',
            name='other_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='additionaloption',
            name='other_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='additionaloption',
            name='other_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
