# Generated by Django 5.1.6 on 2025-12-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_additionaloption_is_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaloption',
            name='other_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
