# Generated by Django 5.2 on 2026-06-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_additionaloption_other_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pythondashboard_role',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('moderator', 'Moderator'), ('event_manager', 'Event Manager'), ('content_moderator', 'Content Moderator')], max_length=30, null=True),
        ),
    ]
