# Generated by Django 5.2 on 2026-07-28 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_review_comment_review_image_1_review_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='host_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='host_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
